event/urls.py
from django.conf.urls import url
from django.urls import path
from .views import new_event, event_detail

app_name = 'event'
urlpatterns = [
    path('new_event/', new_event, name='new_event'),
    path('event_detail/<int:event_id>/', event_detail, name='event_detail')
]

users/urls.py
"""Defines urls for the users"""

from django.conf.urls import url
from django.http import request
from django.urls import path
from django.contrib.auth.views import LoginView
from users.views import signup, logout_view, login_view, test_model_view, dashboard, visitor,\
    direct_message_send, thread

app_name = 'users'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('testform/', test_model_view, name='test_model_view'),
    path('dashboard/<int:user_id>', dashboard, name='dashboard'),
    path('visitor/<int:user_id>', visitor, name='visitor'),
    path('send_message/<int:user_id>', direct_message_send, name= 'direct_message_send'),
    path('thread/<int:dm_id>',thread, name='thread' ),
]

vicarious/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('event/', include('event.urls', namespace='event')),
]

event/models.py
from django.db import models

# Create your models here.
from django.db.models import ForeignKey
from django.contrib.auth.models import User


class Event(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    author = ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.title

    def recent_events(self):
        full_list = Event.objects.all()
        recent_list = full_list[:5]
        return recent_list


class Comment(models.Model):
    description = models.CharField(max_length=1000)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.description


class Reply(models.Model):
    description = models.CharField(max_length=1000)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, blank=True, on_delete=models.CASCADE)
    sub_reply = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)

event/forms.py
from django.forms import ModelForm
from .models import Event, Comment
from django.contrib.auth.decorators import login_required

#all forms below


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description']



class CommentForm(ModelForm):
    class Meta:
        model = Comment
        labels = {"description": "Comment"}
        fields = ['description']

event/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .forms import EventForm, CommentForm
from event.models import Event, Comment, Reply
from django.contrib.auth.decorators import login_required

# Create your views here.


def new_event(request):
    event_new = EventForm
    if request.method == 'POST':
        event_new = EventForm(data=request.POST)
        if event_new.is_valid():
            event = event_new.save(commit=False)
            event.author = request.user
            event.save()
            message = "Event succesfully saved!"
            context = {'message': message, 'event_new': event}
            return render(request, 'users/index.html', context)
        else:
            return HttpResponse("Form was not valid try again")
    else:
        context = {'form': event_new}

        return render(request, 'event/new_event.html', context)


def event_detail(request, event_id):
    detail_event = Event.objects.get(pk=event_id)
    comment_form = CommentForm
    comment_list = Comment.objects.filter(event=event_id)
    context = {'detail_event': detail_event, 'comment_form':comment_form, 'comment_list':comment_list}

    if request.method == 'POST':
        if request.POST['action']=='post comment':
            if not request.user.is_authenticated:
                return render(request, 'users/login.html', context)
            comment_new = CommentForm(data=request.POST)
            if comment_new.is_valid():
                comment = comment_new.save(commit=False)
                comment.author = request.user
                comment.event = detail_event
                comment.save()
                return HttpResponseRedirect('.')
            else:
                return HttpResponse("form not valid")
        elif request.POST['action'] == 'reply':
            reply_new = Reply(description=request.POST['reply'], author=request.user,
                              comment=Comment.objects.get(pk=request.POST['parent_id']))
            reply_new.save()
            return HttpResponseRedirect('.')
    else:
        return render(request, 'event/event_detail.html', context)

event/templates/event/event_detail.html
{% extends 'users/base.html' %}

{% block content %}
<title>Event Detail</title>
<body>
<h2>{{ detail_event.title }}</h2><br>
{{ detail_event.description }}
<br><br>


<form action=""  method="post">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" name="action" value="post comment">
</form>

<br>

<!-- This will show the comments for the event and allow you to post more, also you can click on the user
to go to their profile -->
{% for comment in comment_list %}
    <hr>
    {{ comment.description }}<br>
    - posted by <a href="{% url 'users:dashboard' comment.author.pk %}">{{ comment.author }}</a> <br><br>
    {% for reply in comment.reply_set.all %}
        <li>{{ reply.description }}</li><br>
        {% endfor %}

{# this allows you to reply to either the comment or each reply #}
    <form action= "" method="post">
    {% csrf_token %}

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

    <input type="text" name="reply" value="Type your reply here">
        <input type="submit" name="action" value="reply">
        <input type="hidden" name = 'parent_id' value="{{ comment.pk }}">
    </form>
    <br><br>

{% endfor %}


</body>

{% endblock %}

event/templates/event/new_event.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create New Event</title>
</head>
<body>

Create new event here <br>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create Event">
</form>

</body>
</html>