event/urls.py
from django.conf.urls import url
from django.urls import path
from .views import new_event, event_detail

app_name = 'event'
urlpatterns = [
    path('new_event/', new_event, name='new_event'),
    path('event_detail/<int:event_id>/', event_detail, name='event_detail')
]

users/urls.py
"""Defines urls for the users"""

from django.conf.urls import url
from django.http import request
from django.urls import path
from django.contrib.auth.views import LoginView
from users.views import signup, logout_view, login_view, test_model_view, dashboard, visitor,\
    direct_message_send, thread

app_name = 'users'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('testform/', test_model_view, name='test_model_view'),
    path('dashboard/<int:user_id>', dashboard, name='dashboard'),
    path('visitor/<int:user_id>', visitor, name='visitor'),
    path('send_message/<int:user_id>', direct_message_send, name= 'direct_message_send'),
    path('thread/<int:dm_id>',thread, name='thread' ),
]

vicarious/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('event/', include('event.urls', namespace='event')),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class TestModel(models.Model):
    name = models.CharField(max_length=20)
    last = models.CharField(max_length=30)
    username = models.CharField(max_length=40)

    def __str__(self):
        return self.username


class DirectMessage(models.Model):
    content = models.CharField(max_length=1000)
    sender = models.ForeignKey(User, related_name='sender', on_delete=models.CASCADE)
    recipient = models.ForeignKey(User, related_name='recipient',  on_delete=models.CASCADE)
    sent_at = models.DateTimeField(auto_now_add=True)
    read_at = models.DateTimeField(null=True)
    #TODO how can i do this if there is no parent for the first message created? -see stickies, filter reply = none
    # parent = models.ForeignKey('self', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.content[:100]

    def blurb(self):
        return self.content[:100]


#TODO extend the Direct message model
class DirectMessageReply(models.Model):
    content = models.CharField(max_length=1000)
    # sender = models.ForeignKey(User, related_name='sender', on_delete=models.CASCADE)
    # recipient = models.ForeignKey(User, related_name='recipient_',  on_delete=models.CASCADE)
    sent_at = models.DateTimeField(auto_now_add=True)
    read_at = models.DateTimeField(null=True)
    dm_reply = models.ForeignKey(DirectMessage, related_name='dm_reply', on_delete=models.CASCADE)

users/forms.py
# forms can go here

from django.forms import ModelForm
from .models import TestModel, DirectMessage, DirectMessageReply


class TestModelForm(ModelForm):
    class Meta:
        model = TestModel
        fields = ['name', 'last', 'username']


class DirectMessageForm(ModelForm):
    class Meta:
        model = DirectMessage
        fields = ['content']


class DirectMessageReplyForm(ModelForm):
    class Meta:
        model = DirectMessageReply
        fields = ['content']

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse
from .forms import TestModelForm, DirectMessageForm, DirectMessageReplyForm
from event.models import Event, Comment
from users.models import DirectMessage

# Create your views here.


def index(request):
    template_name = 'users/index.html'
    list_events = Event.objects.all().order_by('-id')[:6]
    context = {'list_events':list_events}
    return render(request,template_name, context)


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
            # the HttpResonseRedirect is there so the page does not ask to confirm
            # form resubmission after every time that you refresh the page
        else:
            return HttpResponse("form not valid try again")
    else:
        form = UserCreationForm
        context = {'form': form}
        template_name = 'users/signup.html'
    return render(request, template_name, context)

# TODO need to create a case that explains what is wrong if the form is not valid, spent a lot
# of time trying to figure out why the user was not saving, it was because i was not meeting requirements, but did not know it



def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return HttpResponseRedirect(reverse('index'))
    else:
        return render(request, 'users/logout.html')


#TODO when this fails it redirects anyways...
def login_view(request):
    list_events = Event.objects.all().order_by('-id')[:6]
    context = {'list_events':list_events}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
        return HttpResponseRedirect(reverse(index), context)
    else:
        return render(request, 'users/login.html')


#TODO need a logged in user dashboard and a non logged in user view
def dashboard(request, user_id):
    user = request.user
    if (user.is_authenticated and user.pk != user_id) or (not user.is_authenticated):
        return redirect('users:visitor', user_id=user_id)
    else:
        events = []
        user = request.user
        user_comment = Comment.objects.filter(author=user)
        #TODO this is not scalable is it?
        user_message = DirectMessage.objects.filter(recipient=user)
        for comment in user_comment:
            event_comment = comment.event
            if event_comment not in events:
                events.append(event_comment)
        context = {'user_comment':user_comment, 'events':events,
                   'user_message':user_message}
        return render(request, 'users/dashboard.html', context)


def test_model_view(request):
    form = TestModelForm
    if request.method == 'POST':
        example = TestModelForm(data=request.POST)
        if example.is_valid():
            mock_user = example.save()
            context = {'mock_user':mock_user}
            return render(request, 'users/index.html', context)
    else:
        context = {'form': form}
        return render(request,'users/testmodel.html', context)


def visitor(request, user_id):
    user_events= User.objects.get(pk=user_id).event_set.all()
    user_home = User.objects.get(pk=user_id)
    context = {'user_events':user_events, 'user_home':user_home}
    return render(request, 'users/visitor.html', context)


def direct_message_send(request, user_id):
    form = DirectMessageForm
    if request.method=='POST':
        new_direct_message = DirectMessageForm(data=request.POST)
        if new_direct_message.is_valid():
            new_direct_message = new_direct_message.save(commit=False)
            new_direct_message.sender = request.user
            new_direct_message.recipient = User.objects.get(pk=user_id)
            #TODO 3
            # new_direct_message.sender = request.user
            # new_direct_message.recipient = User.objects.get(pk=user_id)
            new_direct_message.save()
            #TODO pass this message in the redirect with context
            success = 'Message sent'
            return HttpResponseRedirect(reverse('users:visitor', args=[user_id],))
    else:
        context = {'form': form}
        return render(request, 'users/send_message.html', context)


#TODO 4
def thread(request, dm_id):
    form = DirectMessageReplyForm
    thread = DirectMessage.objects.get(pk=dm_id)
    thread_replies = thread.dm_reply.all()
    context = {'form':form, 'thread_replies':thread_replies}
    if request.method=='POST':
        new_reply = DirectMessageReplyForm(data=request.POST)
        if new_reply.is_valid():
            new_reply = new_reply.save(commit=False)
            new_reply.dm_reply = DirectMessage.objects.get(pk=dm_id) #TODO there has to be a better way to do this, doesnt this just create massive loops?
            new_reply.save()
            return HttpResponseRedirect(reverse('users:thread', args=[dm_id],))
    else:
        return render(request, 'users/thread.html', context)

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">

<p>
    <h1><a href="{% url 'index' %}"style="color: blue">Vicarious Living</a></h1>
    {% if user.is_authenticated %}
    <a href="{% url 'event:new_event' %}" style="color: blue">Create New Event</a>
    <a href="{% url 'users:logout' %}"style="color: blue">Logout</a>
    {% endif %}
    {% if not user.is_authenticated %}
    <a href="{% url 'users:login' %}"style="color: blue">Login Here</a>
    <a href="{% url 'users:signup' %}"style="color: blue">Sign Up Here</a>
    {% endif %}
</p>
<hr>
{% block content %}
{% endblock content %}
</html>

users/templates/users/dashboard.html
{% extends 'users/base.html' %}

{% block content %}


<head>
    <meta charset="UTF-8">
    <title>User Dashboard</title>
</head>
<p>Personal messages:</p>
    {% for message in user_message %}
        Message thread with user:{{ message.sender.username }}
        <li><a href="{% url 'users:thread' message.pk %}">{{ message.blurb }}</a> </li><br>
    {% endfor %}
<hr>

<body>
These are all the comments you have made:
{% for comment in user_comment %}
   <li>{{ comment.description }}</li><br>
    <li>{{ comment.event }}</li>
{% endfor%}

<hr>

These are all the events you have commented on:
{% for event in events %}
    <li>{{ event.title }}</li><br>
{% endfor %}

</body>


{% endblock %}
</html>

users/templates/users/index.html
{% extends 'users/base.html' %}

{% block content %}

<body>
<br>
    {% if user.is_authenticated %}
        Hello {{ user.username }} <br>
        <a href="{% url 'users:dashboard' user.pk %}">Dashboard</a>
    {% endif %}



<h3>Recent Vicarious Living Requests:</h3>
{% for event in list_events %}
    <a href="{% url 'event:event_detail' event.id %}" style="color: blue">{{ event }}</a> <br>
{% endfor %}
  <br>

{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}

<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
</head>

<body>

Login Information
<form method="post">
    {% csrf_token %}
    <input type="text" name="username" value="username">
    <input type="password" name="password" value="password">
    <input type="submit" value="Login">
</form>
</body>

{% endblock %}

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>

{#this form redirects to the index#}
<form method="post">
{% csrf_token %}
    <input type="submit" name="log_me_out" value="Logout">

</form>
</body>
</html>

users/templates/users/send_message.html
{% extends 'users/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send Message">
</form>

{% endblock %}

users/templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>
<body>
Sign Up Here:
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" name="submit" value="Sign Up">
</form>

</body>
</html>

users/templates/users/testmodel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>testmodel</title>
</head>

<body>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="post this">
</form>

</body>
</html>

users/templates/users/thread.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Messages</title>
</head>
<body>
<h1>Inbox</h1><br>
{% for reply in thread_replies %}
    <li>{{ reply.content }} @ {{ reply.sent_at }}</li><br>
{% endfor %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Reply">
</form>
</body>
</html>

users/templates/users/visitor.html
{% extends 'users/base.html' %}

{% block content %}

Requests put in by {{ user_home.username }}
    {% for event in user_events %}
        <li><a href="{% url 'event:event_detail' event.pk %}">{{ event.description }}</a></li>
    {% endfor %}
<br>

Placeholders:
    - send user message <br>
    - about user? bio?


<a href="{% url 'users:direct_message_send' user_home.pk%}">Send User Message</a>

{% endblock %}